#!/bin/bash
# Build and install the "Content Agent" launcher .app to ~/Applications.
#
# RUN_MODE="web-ui": double-clicking the installed app opens a Terminal
# window running ENTRY_CMD in the foreground (Ctrl+C stops it), then opens a
# browser tab once it's up.
#
# RUN_MODE="pipeline": double-clicking runs ENTRY_CMD once to completion —
# for a one-shot agent (the kind normally driven by a scheduled CI job)
# rather than a server. The window stays open with the output on screen
# until you press Return, instead of vanishing the moment the command exits.
#
# Safe to re-run — overwrites any previous build.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="Content Agent"
RUN_MODE="web-ui" # "web-ui" or "pipeline"
ENTRY_CMD="uv run uvicorn web.main:app --port 8000" # pipeline mode: e.g. "uv run python scripts/run_pipeline.py"
INSTALL_DIR="$HOME/Applications"
BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

echo "Rendering icon..."
ICONSET="$BUILD_DIR/icon.iconset"
uv run --with pillow python "$PROJECT_DIR/scripts/render_emoji_icon.py" "💡" "$ICONSET"
iconutil -c icns "$ICONSET" -o "$BUILD_DIR/icon.icns"

echo "Assembling app bundle..."
APP_DIR="$BUILD_DIR/$APP_NAME.app"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$BUILD_DIR/icon.icns" "$APP_DIR/Contents/Resources/icon.icns"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.tmtabor.content-agent-launcher</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIconFile</key>
    <string>icon.icns</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.13</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

if [ "$RUN_MODE" = "web-ui" ]; then
cat > "$APP_DIR/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Generated by scripts/build_launcher.sh — re-run that script to regenerate,
# don't hand-edit (PROJECT_DIR/ENTRY_CMD below are baked in at build time).
PROJECT_DIR="$PROJECT_DIR"
ENTRY_CMD="$ENTRY_CMD"

osascript <<APPLESCRIPT
tell application "Terminal"
    activate
    do script "cd '\$PROJECT_DIR' && exec \$ENTRY_CMD"
end tell
APPLESCRIPT

# Give the server a moment to start, then open the browser. Keep this port
# in sync with ENTRY_CMD above.
(sleep 2 && open "http://localhost:8000") &
LAUNCHER
else
cat > "$APP_DIR/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Generated by scripts/build_launcher.sh — re-run that script to regenerate,
# don't hand-edit (PROJECT_DIR/ENTRY_CMD below are baked in at build time).
PROJECT_DIR="$PROJECT_DIR"
ENTRY_CMD="$ENTRY_CMD"

osascript <<APPLESCRIPT
tell application "Terminal"
    activate
    do script "cd '\$PROJECT_DIR' && \$ENTRY_CMD; echo; echo Run finished. Press Return to close this window.; read"
end tell
APPLESCRIPT
LAUNCHER
fi
chmod +x "$APP_DIR/Contents/MacOS/launcher"

echo "Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
rm -rf "$INSTALL_DIR/$APP_NAME.app"
cp -R "$APP_DIR" "$INSTALL_DIR/"

echo "Done: $INSTALL_DIR/$APP_NAME.app"
